// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: variant.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Fmq.Finalmq.Variant {

  /// <summary>Holder for reflection information generated from variant.proto</summary>
  public static partial class VariantReflection {

    #region Descriptor
    /// <summary>File descriptor for variant.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VariantReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg12YXJpYW50LnByb3RvEhNmbXEuZmluYWxtcS52YXJpYW50ItsDCghWYXJW",
            "YWx1ZRIMCgRuYW1lGAEgASgJEiwKBHR5cGUYAiABKA4yHi5mbXEuZmluYWxt",
            "cS52YXJpYW50LlZhclR5cGVJZBIPCgd2YWxib29sGAMgASgIEhAKCHZhbGlu",
            "dDMyGAQgASgPEhEKCXZhbHVpbnQzMhgFIAEoBxIQCgh2YWxpbnQ2NBgGIAEo",
            "EBIRCgl2YWx1aW50NjQYByABKAYSEAoIdmFsZmxvYXQYCCABKAISEQoJdmFs",
            "ZG91YmxlGAkgASgBEhEKCXZhbHN0cmluZxgKIAEoCRIQCgh2YWxieXRlcxgL",
            "IAEoDBIuCgd2YWxsaXN0GAwgAygLMh0uZm1xLmZpbmFsbXEudmFyaWFudC5W",
            "YXJWYWx1ZRISCgp2YWxhcnJib29sGA0gAygIEhMKC3ZhbGFycmludDMyGA4g",
            "AygPEhQKDHZhbGFycnVpbnQzMhgPIAMoBxITCgt2YWxhcnJpbnQ2NBgQIAMo",
            "EBIUCgx2YWxhcnJ1aW50NjQYESADKAYSEwoLdmFsYXJyZmxvYXQYEiADKAIS",
            "FAoMdmFsYXJyZG91YmxlGBMgAygBEhQKDHZhbGFycnN0cmluZxgUIAMoCRIT",
            "Cgt2YWxhcnJieXRlcxgVIAMoDCrhAgoJVmFyVHlwZUlkEgoKBlRfTk9ORRAA",
            "EgoKBlRfQk9PTBABEgsKB1RfSU5UMzIQAhIMCghUX1VJTlQzMhADEgsKB1Rf",
            "SU5UNjQQBBIMCghUX1VJTlQ2NBAFEgsKB1RfRkxPQVQQBhIMCghUX0RPVUJM",
            "RRAHEgwKCFRfU1RSSU5HEAgSCwoHVF9CWVRFUxAJEgwKCFRfU1RSVUNUEAoS",
            "EQoMVF9BUlJBWV9CT09MEIEIEhIKDVRfQVJSQVlfSU5UMzIQgggSEwoOVF9B",
            "UlJBWV9VSU5UMzIQgwgSEgoNVF9BUlJBWV9JTlQ2NBCECBITCg5UX0FSUkFZ",
            "X1VJTlQ2NBCFCBISCg1UX0FSUkFZX0ZMT0FUEIYIEhMKDlRfQVJSQVlfRE9V",
            "QkxFEIcIEhMKDlRfQVJSQVlfU1RSSU5HEIgIEhIKDVRfQVJSQVlfQllURVMQ",
            "iQgSCwoGVF9MSVNUEIoIYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Fmq.Finalmq.Variant.VarTypeId), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Fmq.Finalmq.Variant.VarValue), global::Fmq.Finalmq.Variant.VarValue.Parser, new[]{ "Name", "Type", "Valbool", "Valint32", "Valuint32", "Valint64", "Valuint64", "Valfloat", "Valdouble", "Valstring", "Valbytes", "Vallist", "Valarrbool", "Valarrint32", "Valarruint32", "Valarrint64", "Valarruint64", "Valarrfloat", "Valarrdouble", "Valarrstring", "Valarrbytes" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum VarTypeId {
    [pbr::OriginalName("T_NONE")] TNone = 0,
    [pbr::OriginalName("T_BOOL")] TBool = 1,
    [pbr::OriginalName("T_INT32")] TInt32 = 2,
    [pbr::OriginalName("T_UINT32")] TUint32 = 3,
    [pbr::OriginalName("T_INT64")] TInt64 = 4,
    [pbr::OriginalName("T_UINT64")] TUint64 = 5,
    [pbr::OriginalName("T_FLOAT")] TFloat = 6,
    [pbr::OriginalName("T_DOUBLE")] TDouble = 7,
    [pbr::OriginalName("T_STRING")] TString = 8,
    [pbr::OriginalName("T_BYTES")] TBytes = 9,
    [pbr::OriginalName("T_STRUCT")] TStruct = 10,
    [pbr::OriginalName("T_ARRAY_BOOL")] TArrayBool = 1025,
    [pbr::OriginalName("T_ARRAY_INT32")] TArrayInt32 = 1026,
    [pbr::OriginalName("T_ARRAY_UINT32")] TArrayUint32 = 1027,
    [pbr::OriginalName("T_ARRAY_INT64")] TArrayInt64 = 1028,
    [pbr::OriginalName("T_ARRAY_UINT64")] TArrayUint64 = 1029,
    [pbr::OriginalName("T_ARRAY_FLOAT")] TArrayFloat = 1030,
    [pbr::OriginalName("T_ARRAY_DOUBLE")] TArrayDouble = 1031,
    [pbr::OriginalName("T_ARRAY_STRING")] TArrayString = 1032,
    [pbr::OriginalName("T_ARRAY_BYTES")] TArrayBytes = 1033,
    [pbr::OriginalName("T_LIST")] TList = 1034,
  }

  #endregion

  #region Messages
  public sealed partial class VarValue : pb::IMessage<VarValue>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VarValue> _parser = new pb::MessageParser<VarValue>(() => new VarValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VarValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Fmq.Finalmq.Variant.VariantReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VarValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VarValue(VarValue other) : this() {
      name_ = other.name_;
      type_ = other.type_;
      valbool_ = other.valbool_;
      valint32_ = other.valint32_;
      valuint32_ = other.valuint32_;
      valint64_ = other.valint64_;
      valuint64_ = other.valuint64_;
      valfloat_ = other.valfloat_;
      valdouble_ = other.valdouble_;
      valstring_ = other.valstring_;
      valbytes_ = other.valbytes_;
      vallist_ = other.vallist_.Clone();
      valarrbool_ = other.valarrbool_.Clone();
      valarrint32_ = other.valarrint32_.Clone();
      valarruint32_ = other.valarruint32_.Clone();
      valarrint64_ = other.valarrint64_.Clone();
      valarruint64_ = other.valarruint64_.Clone();
      valarrfloat_ = other.valarrfloat_.Clone();
      valarrdouble_ = other.valarrdouble_.Clone();
      valarrstring_ = other.valarrstring_.Clone();
      valarrbytes_ = other.valarrbytes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VarValue Clone() {
      return new VarValue(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Fmq.Finalmq.Variant.VarTypeId type_ = global::Fmq.Finalmq.Variant.VarTypeId.TNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Fmq.Finalmq.Variant.VarTypeId Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "valbool" field.</summary>
    public const int ValboolFieldNumber = 3;
    private bool valbool_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Valbool {
      get { return valbool_; }
      set {
        valbool_ = value;
      }
    }

    /// <summary>Field number for the "valint32" field.</summary>
    public const int Valint32FieldNumber = 4;
    private int valint32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Valint32 {
      get { return valint32_; }
      set {
        valint32_ = value;
      }
    }

    /// <summary>Field number for the "valuint32" field.</summary>
    public const int Valuint32FieldNumber = 5;
    private uint valuint32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Valuint32 {
      get { return valuint32_; }
      set {
        valuint32_ = value;
      }
    }

    /// <summary>Field number for the "valint64" field.</summary>
    public const int Valint64FieldNumber = 6;
    private long valint64_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Valint64 {
      get { return valint64_; }
      set {
        valint64_ = value;
      }
    }

    /// <summary>Field number for the "valuint64" field.</summary>
    public const int Valuint64FieldNumber = 7;
    private ulong valuint64_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Valuint64 {
      get { return valuint64_; }
      set {
        valuint64_ = value;
      }
    }

    /// <summary>Field number for the "valfloat" field.</summary>
    public const int ValfloatFieldNumber = 8;
    private float valfloat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Valfloat {
      get { return valfloat_; }
      set {
        valfloat_ = value;
      }
    }

    /// <summary>Field number for the "valdouble" field.</summary>
    public const int ValdoubleFieldNumber = 9;
    private double valdouble_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Valdouble {
      get { return valdouble_; }
      set {
        valdouble_ = value;
      }
    }

    /// <summary>Field number for the "valstring" field.</summary>
    public const int ValstringFieldNumber = 10;
    private string valstring_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Valstring {
      get { return valstring_; }
      set {
        valstring_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "valbytes" field.</summary>
    public const int ValbytesFieldNumber = 11;
    private pb::ByteString valbytes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Valbytes {
      get { return valbytes_; }
      set {
        valbytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "vallist" field.</summary>
    public const int VallistFieldNumber = 12;
    private static readonly pb::FieldCodec<global::Fmq.Finalmq.Variant.VarValue> _repeated_vallist_codec
        = pb::FieldCodec.ForMessage(98, global::Fmq.Finalmq.Variant.VarValue.Parser);
    private readonly pbc::RepeatedField<global::Fmq.Finalmq.Variant.VarValue> vallist_ = new pbc::RepeatedField<global::Fmq.Finalmq.Variant.VarValue>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Fmq.Finalmq.Variant.VarValue> Vallist {
      get { return vallist_; }
    }

    /// <summary>Field number for the "valarrbool" field.</summary>
    public const int ValarrboolFieldNumber = 13;
    private static readonly pb::FieldCodec<bool> _repeated_valarrbool_codec
        = pb::FieldCodec.ForBool(106);
    private readonly pbc::RepeatedField<bool> valarrbool_ = new pbc::RepeatedField<bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<bool> Valarrbool {
      get { return valarrbool_; }
    }

    /// <summary>Field number for the "valarrint32" field.</summary>
    public const int Valarrint32FieldNumber = 14;
    private static readonly pb::FieldCodec<int> _repeated_valarrint32_codec
        = pb::FieldCodec.ForSFixed32(114);
    private readonly pbc::RepeatedField<int> valarrint32_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Valarrint32 {
      get { return valarrint32_; }
    }

    /// <summary>Field number for the "valarruint32" field.</summary>
    public const int Valarruint32FieldNumber = 15;
    private static readonly pb::FieldCodec<uint> _repeated_valarruint32_codec
        = pb::FieldCodec.ForFixed32(122);
    private readonly pbc::RepeatedField<uint> valarruint32_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Valarruint32 {
      get { return valarruint32_; }
    }

    /// <summary>Field number for the "valarrint64" field.</summary>
    public const int Valarrint64FieldNumber = 16;
    private static readonly pb::FieldCodec<long> _repeated_valarrint64_codec
        = pb::FieldCodec.ForSFixed64(130);
    private readonly pbc::RepeatedField<long> valarrint64_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> Valarrint64 {
      get { return valarrint64_; }
    }

    /// <summary>Field number for the "valarruint64" field.</summary>
    public const int Valarruint64FieldNumber = 17;
    private static readonly pb::FieldCodec<ulong> _repeated_valarruint64_codec
        = pb::FieldCodec.ForFixed64(138);
    private readonly pbc::RepeatedField<ulong> valarruint64_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<ulong> Valarruint64 {
      get { return valarruint64_; }
    }

    /// <summary>Field number for the "valarrfloat" field.</summary>
    public const int ValarrfloatFieldNumber = 18;
    private static readonly pb::FieldCodec<float> _repeated_valarrfloat_codec
        = pb::FieldCodec.ForFloat(146);
    private readonly pbc::RepeatedField<float> valarrfloat_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Valarrfloat {
      get { return valarrfloat_; }
    }

    /// <summary>Field number for the "valarrdouble" field.</summary>
    public const int ValarrdoubleFieldNumber = 19;
    private static readonly pb::FieldCodec<double> _repeated_valarrdouble_codec
        = pb::FieldCodec.ForDouble(154);
    private readonly pbc::RepeatedField<double> valarrdouble_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Valarrdouble {
      get { return valarrdouble_; }
    }

    /// <summary>Field number for the "valarrstring" field.</summary>
    public const int ValarrstringFieldNumber = 20;
    private static readonly pb::FieldCodec<string> _repeated_valarrstring_codec
        = pb::FieldCodec.ForString(162);
    private readonly pbc::RepeatedField<string> valarrstring_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Valarrstring {
      get { return valarrstring_; }
    }

    /// <summary>Field number for the "valarrbytes" field.</summary>
    public const int ValarrbytesFieldNumber = 21;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_valarrbytes_codec
        = pb::FieldCodec.ForBytes(170);
    private readonly pbc::RepeatedField<pb::ByteString> valarrbytes_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> Valarrbytes {
      get { return valarrbytes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VarValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VarValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      if (Valbool != other.Valbool) return false;
      if (Valint32 != other.Valint32) return false;
      if (Valuint32 != other.Valuint32) return false;
      if (Valint64 != other.Valint64) return false;
      if (Valuint64 != other.Valuint64) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Valfloat, other.Valfloat)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Valdouble, other.Valdouble)) return false;
      if (Valstring != other.Valstring) return false;
      if (Valbytes != other.Valbytes) return false;
      if(!vallist_.Equals(other.vallist_)) return false;
      if(!valarrbool_.Equals(other.valarrbool_)) return false;
      if(!valarrint32_.Equals(other.valarrint32_)) return false;
      if(!valarruint32_.Equals(other.valarruint32_)) return false;
      if(!valarrint64_.Equals(other.valarrint64_)) return false;
      if(!valarruint64_.Equals(other.valarruint64_)) return false;
      if(!valarrfloat_.Equals(other.valarrfloat_)) return false;
      if(!valarrdouble_.Equals(other.valarrdouble_)) return false;
      if(!valarrstring_.Equals(other.valarrstring_)) return false;
      if(!valarrbytes_.Equals(other.valarrbytes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type != global::Fmq.Finalmq.Variant.VarTypeId.TNone) hash ^= Type.GetHashCode();
      if (Valbool != false) hash ^= Valbool.GetHashCode();
      if (Valint32 != 0) hash ^= Valint32.GetHashCode();
      if (Valuint32 != 0) hash ^= Valuint32.GetHashCode();
      if (Valint64 != 0L) hash ^= Valint64.GetHashCode();
      if (Valuint64 != 0UL) hash ^= Valuint64.GetHashCode();
      if (Valfloat != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Valfloat);
      if (Valdouble != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Valdouble);
      if (Valstring.Length != 0) hash ^= Valstring.GetHashCode();
      if (Valbytes.Length != 0) hash ^= Valbytes.GetHashCode();
      hash ^= vallist_.GetHashCode();
      hash ^= valarrbool_.GetHashCode();
      hash ^= valarrint32_.GetHashCode();
      hash ^= valarruint32_.GetHashCode();
      hash ^= valarrint64_.GetHashCode();
      hash ^= valarruint64_.GetHashCode();
      hash ^= valarrfloat_.GetHashCode();
      hash ^= valarrdouble_.GetHashCode();
      hash ^= valarrstring_.GetHashCode();
      hash ^= valarrbytes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != global::Fmq.Finalmq.Variant.VarTypeId.TNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Valbool != false) {
        output.WriteRawTag(24);
        output.WriteBool(Valbool);
      }
      if (Valint32 != 0) {
        output.WriteRawTag(37);
        output.WriteSFixed32(Valint32);
      }
      if (Valuint32 != 0) {
        output.WriteRawTag(45);
        output.WriteFixed32(Valuint32);
      }
      if (Valint64 != 0L) {
        output.WriteRawTag(49);
        output.WriteSFixed64(Valint64);
      }
      if (Valuint64 != 0UL) {
        output.WriteRawTag(57);
        output.WriteFixed64(Valuint64);
      }
      if (Valfloat != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Valfloat);
      }
      if (Valdouble != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Valdouble);
      }
      if (Valstring.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Valstring);
      }
      if (Valbytes.Length != 0) {
        output.WriteRawTag(90);
        output.WriteBytes(Valbytes);
      }
      vallist_.WriteTo(output, _repeated_vallist_codec);
      valarrbool_.WriteTo(output, _repeated_valarrbool_codec);
      valarrint32_.WriteTo(output, _repeated_valarrint32_codec);
      valarruint32_.WriteTo(output, _repeated_valarruint32_codec);
      valarrint64_.WriteTo(output, _repeated_valarrint64_codec);
      valarruint64_.WriteTo(output, _repeated_valarruint64_codec);
      valarrfloat_.WriteTo(output, _repeated_valarrfloat_codec);
      valarrdouble_.WriteTo(output, _repeated_valarrdouble_codec);
      valarrstring_.WriteTo(output, _repeated_valarrstring_codec);
      valarrbytes_.WriteTo(output, _repeated_valarrbytes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != global::Fmq.Finalmq.Variant.VarTypeId.TNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (Valbool != false) {
        output.WriteRawTag(24);
        output.WriteBool(Valbool);
      }
      if (Valint32 != 0) {
        output.WriteRawTag(37);
        output.WriteSFixed32(Valint32);
      }
      if (Valuint32 != 0) {
        output.WriteRawTag(45);
        output.WriteFixed32(Valuint32);
      }
      if (Valint64 != 0L) {
        output.WriteRawTag(49);
        output.WriteSFixed64(Valint64);
      }
      if (Valuint64 != 0UL) {
        output.WriteRawTag(57);
        output.WriteFixed64(Valuint64);
      }
      if (Valfloat != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Valfloat);
      }
      if (Valdouble != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Valdouble);
      }
      if (Valstring.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Valstring);
      }
      if (Valbytes.Length != 0) {
        output.WriteRawTag(90);
        output.WriteBytes(Valbytes);
      }
      vallist_.WriteTo(ref output, _repeated_vallist_codec);
      valarrbool_.WriteTo(ref output, _repeated_valarrbool_codec);
      valarrint32_.WriteTo(ref output, _repeated_valarrint32_codec);
      valarruint32_.WriteTo(ref output, _repeated_valarruint32_codec);
      valarrint64_.WriteTo(ref output, _repeated_valarrint64_codec);
      valarruint64_.WriteTo(ref output, _repeated_valarruint64_codec);
      valarrfloat_.WriteTo(ref output, _repeated_valarrfloat_codec);
      valarrdouble_.WriteTo(ref output, _repeated_valarrdouble_codec);
      valarrstring_.WriteTo(ref output, _repeated_valarrstring_codec);
      valarrbytes_.WriteTo(ref output, _repeated_valarrbytes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type != global::Fmq.Finalmq.Variant.VarTypeId.TNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Valbool != false) {
        size += 1 + 1;
      }
      if (Valint32 != 0) {
        size += 1 + 4;
      }
      if (Valuint32 != 0) {
        size += 1 + 4;
      }
      if (Valint64 != 0L) {
        size += 1 + 8;
      }
      if (Valuint64 != 0UL) {
        size += 1 + 8;
      }
      if (Valfloat != 0F) {
        size += 1 + 4;
      }
      if (Valdouble != 0D) {
        size += 1 + 8;
      }
      if (Valstring.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Valstring);
      }
      if (Valbytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Valbytes);
      }
      size += vallist_.CalculateSize(_repeated_vallist_codec);
      size += valarrbool_.CalculateSize(_repeated_valarrbool_codec);
      size += valarrint32_.CalculateSize(_repeated_valarrint32_codec);
      size += valarruint32_.CalculateSize(_repeated_valarruint32_codec);
      size += valarrint64_.CalculateSize(_repeated_valarrint64_codec);
      size += valarruint64_.CalculateSize(_repeated_valarruint64_codec);
      size += valarrfloat_.CalculateSize(_repeated_valarrfloat_codec);
      size += valarrdouble_.CalculateSize(_repeated_valarrdouble_codec);
      size += valarrstring_.CalculateSize(_repeated_valarrstring_codec);
      size += valarrbytes_.CalculateSize(_repeated_valarrbytes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VarValue other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type != global::Fmq.Finalmq.Variant.VarTypeId.TNone) {
        Type = other.Type;
      }
      if (other.Valbool != false) {
        Valbool = other.Valbool;
      }
      if (other.Valint32 != 0) {
        Valint32 = other.Valint32;
      }
      if (other.Valuint32 != 0) {
        Valuint32 = other.Valuint32;
      }
      if (other.Valint64 != 0L) {
        Valint64 = other.Valint64;
      }
      if (other.Valuint64 != 0UL) {
        Valuint64 = other.Valuint64;
      }
      if (other.Valfloat != 0F) {
        Valfloat = other.Valfloat;
      }
      if (other.Valdouble != 0D) {
        Valdouble = other.Valdouble;
      }
      if (other.Valstring.Length != 0) {
        Valstring = other.Valstring;
      }
      if (other.Valbytes.Length != 0) {
        Valbytes = other.Valbytes;
      }
      vallist_.Add(other.vallist_);
      valarrbool_.Add(other.valarrbool_);
      valarrint32_.Add(other.valarrint32_);
      valarruint32_.Add(other.valarruint32_);
      valarrint64_.Add(other.valarrint64_);
      valarruint64_.Add(other.valarruint64_);
      valarrfloat_.Add(other.valarrfloat_);
      valarrdouble_.Add(other.valarrdouble_);
      valarrstring_.Add(other.valarrstring_);
      valarrbytes_.Add(other.valarrbytes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Fmq.Finalmq.Variant.VarTypeId) input.ReadEnum();
            break;
          }
          case 24: {
            Valbool = input.ReadBool();
            break;
          }
          case 37: {
            Valint32 = input.ReadSFixed32();
            break;
          }
          case 45: {
            Valuint32 = input.ReadFixed32();
            break;
          }
          case 49: {
            Valint64 = input.ReadSFixed64();
            break;
          }
          case 57: {
            Valuint64 = input.ReadFixed64();
            break;
          }
          case 69: {
            Valfloat = input.ReadFloat();
            break;
          }
          case 73: {
            Valdouble = input.ReadDouble();
            break;
          }
          case 82: {
            Valstring = input.ReadString();
            break;
          }
          case 90: {
            Valbytes = input.ReadBytes();
            break;
          }
          case 98: {
            vallist_.AddEntriesFrom(input, _repeated_vallist_codec);
            break;
          }
          case 106:
          case 104: {
            valarrbool_.AddEntriesFrom(input, _repeated_valarrbool_codec);
            break;
          }
          case 114:
          case 117: {
            valarrint32_.AddEntriesFrom(input, _repeated_valarrint32_codec);
            break;
          }
          case 122:
          case 125: {
            valarruint32_.AddEntriesFrom(input, _repeated_valarruint32_codec);
            break;
          }
          case 130:
          case 129: {
            valarrint64_.AddEntriesFrom(input, _repeated_valarrint64_codec);
            break;
          }
          case 138:
          case 137: {
            valarruint64_.AddEntriesFrom(input, _repeated_valarruint64_codec);
            break;
          }
          case 146:
          case 149: {
            valarrfloat_.AddEntriesFrom(input, _repeated_valarrfloat_codec);
            break;
          }
          case 154:
          case 153: {
            valarrdouble_.AddEntriesFrom(input, _repeated_valarrdouble_codec);
            break;
          }
          case 162: {
            valarrstring_.AddEntriesFrom(input, _repeated_valarrstring_codec);
            break;
          }
          case 170: {
            valarrbytes_.AddEntriesFrom(input, _repeated_valarrbytes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Fmq.Finalmq.Variant.VarTypeId) input.ReadEnum();
            break;
          }
          case 24: {
            Valbool = input.ReadBool();
            break;
          }
          case 37: {
            Valint32 = input.ReadSFixed32();
            break;
          }
          case 45: {
            Valuint32 = input.ReadFixed32();
            break;
          }
          case 49: {
            Valint64 = input.ReadSFixed64();
            break;
          }
          case 57: {
            Valuint64 = input.ReadFixed64();
            break;
          }
          case 69: {
            Valfloat = input.ReadFloat();
            break;
          }
          case 73: {
            Valdouble = input.ReadDouble();
            break;
          }
          case 82: {
            Valstring = input.ReadString();
            break;
          }
          case 90: {
            Valbytes = input.ReadBytes();
            break;
          }
          case 98: {
            vallist_.AddEntriesFrom(ref input, _repeated_vallist_codec);
            break;
          }
          case 106:
          case 104: {
            valarrbool_.AddEntriesFrom(ref input, _repeated_valarrbool_codec);
            break;
          }
          case 114:
          case 117: {
            valarrint32_.AddEntriesFrom(ref input, _repeated_valarrint32_codec);
            break;
          }
          case 122:
          case 125: {
            valarruint32_.AddEntriesFrom(ref input, _repeated_valarruint32_codec);
            break;
          }
          case 130:
          case 129: {
            valarrint64_.AddEntriesFrom(ref input, _repeated_valarrint64_codec);
            break;
          }
          case 138:
          case 137: {
            valarruint64_.AddEntriesFrom(ref input, _repeated_valarruint64_codec);
            break;
          }
          case 146:
          case 149: {
            valarrfloat_.AddEntriesFrom(ref input, _repeated_valarrfloat_codec);
            break;
          }
          case 154:
          case 153: {
            valarrdouble_.AddEntriesFrom(ref input, _repeated_valarrdouble_codec);
            break;
          }
          case 162: {
            valarrstring_.AddEntriesFrom(ref input, _repeated_valarrstring_codec);
            break;
          }
          case 170: {
            valarrbytes_.AddEntriesFrom(ref input, _repeated_valarrbytes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
